### ISSUE TITLE
speed up loading manga covers (maybe tachidesk specific)[FEATURE]

### ISSUE THREAD

**Issue by Robonau** [JiPaix/Fukayo#453]
**Is your feature request related to a problem? Please describe.**
as it is right now i can't actually load my whole tachidesk library because of how it loads one at a time

i have ~400 manga on tachidesk when clicking explore on tachidesk i get maybe a dozen before it fails
and what does load takes ages as it is doing every manga one by one rather than asynchronously

**Describe the solution you'd like**
either lazy loading the images or just doing all the requests simultaneously (tachidesk can handle it)

**Describe alternatives you've considered**
none

**Additional context**

**Comment by JiPaix** [comment]
#455 partially solves it, **but**:

I think #330, #332 and #338 will be more inline with what you are expecting as it won't be straight up import but will offer the option to navigate/select entries more easily.

The "Explore" tab might be confusing and should probably renamed, the intent is to show mangas that are featured (or the latest releases) on the source. Like if you want to read something new but you aren't inspired you'd check this tab.

But out of laziness I decided that Komga and Tachidesk should display their whole collections until those PR are closed.

Once #330 is complete:
- "Exploring" Tachidesk will probably only shows what's in `api/v1/update/recentChapters`
- and Komga's `/api/v1/books/latest`

**Comment by Robonau** [comment]
my latest pr #457 has solved this issue
it's now blazing fast at loading tachidesk manga
