### ISSUE TITLE
[BUG] Fukayo does not remember Source settings

### ISSUE THREAD

**Issue by ghost** [JiPaix/Fukayo#685]
**Describe the bug**
Source setting problem was described in [discord](https://discord.com/channels/1028374527492759582/1028377641327263794/1073274147347644436)
**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Sources'
3. Scroll down to 'Tachidesk'
4. Put your credentials and refresh to page

**Expected behavior**
It should remember credentials even though I refreshed the page
**Screenshots**
before refresh 
![image](https://user-images.githubusercontent.com/43301560/221356017-c19bf155-32ba-4af2-b479-157fee027b4a.png)
after refresh
![image](https://user-images.githubusercontent.com/43301560/221356030-8a732888-ad7e-4b46-b61f-936da3675b9b.png)

**Additional context**
It shows that Tachidesk is not configured but I can import mangas from there also explore does not work on (it cant see tachidesk)

**Comment by JiPaix** [comment]
closed by e867b57
